/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NovoRouteImport } from './routes/novo'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as DefinicoesRouteImport } from './routes/definicoes'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoRoute = NovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinicoesRoute = DefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/definicoes': typeof DefinicoesRoute
  '/historico': typeof HistoricoRoute
  '/novo': typeof NovoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/definicoes': typeof DefinicoesRoute
  '/historico': typeof HistoricoRoute
  '/novo': typeof NovoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/definicoes': typeof DefinicoesRoute
  '/historico': typeof HistoricoRoute
  '/novo': typeof NovoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/definicoes'
    | '/historico'
    | '/novo'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/definicoes'
    | '/historico'
    | '/novo'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/definicoes'
    | '/historico'
    | '/novo'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  DefinicoesRoute: typeof DefinicoesRoute
  HistoricoRoute: typeof HistoricoRoute
  NovoRoute: typeof NovoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo': {
      id: '/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof NovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definicoes': {
      id: '/definicoes'
      path: '/definicoes'
      fullPath: '/definicoes'
      preLoaderRoute: typeof DefinicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  DefinicoesRoute: DefinicoesRoute,
  HistoricoRoute: HistoricoRoute,
  NovoRoute: NovoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
